language: python
python:
  - 2.5
  - 2.6
  - 2.7
install:
  - if [ $TRAVIS_PYTHON_VERSION == '2.5' ]; then pip install -r python25-requirements.txt --use-mirrors; else pip install -r requirements.txt --use-mirrors; fi
script: nosetests --with-coverage --cover-erase --cover-package=createsend --cover-html
after_script:
  - if [ $TRAVIS_PYTHON_VERSION != '2.5' ]; then coveralls; fi
